/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    theme: {
        extend: {
            fontFamily: {
                serif: ['"Cormorant Garamond"', 'Georgia', 'serif'],
                sans: ['"Outfit"', 'system-ui', 'sans-serif'],
                mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
                playfair: ['"Playfair Display"', 'serif'],
                manrope: ['"Manrope"', 'system-ui', 'sans-serif'],
                cabinet: ['"Cabinet Grotesk"', 'system-ui', 'sans-serif'],
                figtree: ['"Figtree"', 'system-ui', 'sans-serif'],
                clash: ['"Clash Display"', 'system-ui', 'sans-serif'],
                satoshi: ['"Satoshi"', 'system-ui', 'sans-serif'],
                'product-sans': ['"Google Sans"', '"Product Sans"', 'system-ui', 'sans-serif'],
                roboto: ['"Roboto"', 'system-ui', 'sans-serif'],
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            colors: {
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
                popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
                primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
                secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
                muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
                accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
                destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
            },
            keyframes: {
                'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
                'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
                marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
                'marquee-fast': { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
                'fade-up': { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
                'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
                'blink': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
                'marquee': 'marquee 40s linear infinite',
                'marquee-fast': 'marquee-fast 18s linear infinite',
                'fade-up': 'fade-up 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards',
                'fade-in': 'fade-in 0.6s ease forwards',
                'blink': 'blink 1s steps(2) infinite',
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
